In [93]:
## Q1: Write a function so that the columns of the output matrix are powers of the input vector. 

import numpy as np
   
def gen_vander_matrix(inputvector, n, increasing=False):
    
    if increasing==False:
        op_matx = np.array([x**(n-1-i) for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
    elif increasing==True:
        op_matx = np.array([x**i for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
    
    return op_matx

print("------------OUTPUT-------------\n")

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 5
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print("Input array is:",inputvector,"\n")
print("Number of columns in output matrix:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

------------OUTPUT-------------

Input array is: [1 2 3 4 5] 

Number of columns in output matrix: 5 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 



In [90]:
## Q2: Write a function to find moving average in an array over a window

import numpy as np

def moving_average(input_vector, window_size) :
    ma = np.cumsum(input_vector, dtype=float)
    x=ma[window_size-1]
    ma=ma[window_size:]-ma[:-window_size]
    ma=np.insert(ma,0,x)
    print("---------Moving Average----------","\n")
    print(list(ma/window_size))

In [91]:
input_vector = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size = 3
moving_average(input_vector,window_size)

---------Moving Average---------- 

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
